Add item requests
EvgeniyaLapteva/java-shareit pull request #3
Opened 2023-07-14 12:00 UTC by EvgeniyaLapteva

2023-07-15 12:22 UTC, z8q requested changes

2023-07-15 12:22 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Похоже не хватает тестов для слоя репозиториев с использованием `@DataJpaTest`

2023-07-16 04:22 UTC, EvgeniyaLapteva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Сделано!

2023-07-16 10:04 UTC, z8q approved these changes

2023-07-16 14:15 UTC, merged