Add docker
EvgeniyaLapteva/java-shareit pull request #4
Opened 2023-07-24 21:59 UTC by EvgeniyaLapteva

2023-07-25 18:02 UTC, z8q requested changes

2023-07-25 18:02 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +		if (!requestDto.getEnd().isAfter(requestDto.getStart()) || requestDto.getEnd().equals(requestDto.getStart())) {
в контроллере появляется логика, лучше ее все таки убирать на уровень ниже. В контроллере оставить только вызовы и логирование

2023-07-25 18:02 UTC, z8q commented on docker-compose.yml
> +      - db
тут можно оставить только -server
последовательность выполнения останется такой же
db -> server -> gateway

2023-07-25 19:33 UTC, EvgeniyaLapteva commented on docker-compose.yml
> +      - db
Сделано!

2023-07-25 19:33 UTC, EvgeniyaLapteva commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +		if (!requestDto.getEnd().isAfter(requestDto.getStart()) || requestDto.getEnd().equals(requestDto.getStart())) {
Убрала логику из контроллеров

2023-07-26 23:58 UTC, z8q approved these changes

2023-07-27 09:53 UTC, merged